import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Destinos from '@/components/Destinos'
import Viajantes from '@/components/Viajantes'
import Compras from '@/components/Compras'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const[lista,setLista]=useState("Viajantes")

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main>
        <select 
        onChange={e=>setLista(e.target.value)}
        >
          <option value={"Viajantes"}>Viajantes</option>
          <option value={"Destinos"}>Destinos</option>
          <option value={"Compras"}>Compras</option>
        </select>
      <div className="p-4">
				
        {lista==="Destinos"&&<Destinos />}
        {lista==="Viajantes"&&<Viajantes />}
        {lista==="Compras"&&<Compras />}

			</div>
      </main>
    </>
  )
}
